### ISSUE TITLE
Not compatible with TypeScript 5.0

### ISSUE THREAD

**Issue by zaguiini** [zaguiini/typescript-virtual-barrel#4]
Currently the plugins are limited to TS 4. Some progress in https://github.com/zaguiini/typescript-virtual-barrel/tree/fix/update-ts-5.

**Comment by diegovilar** [comment]
Any progress on this front, sir? This plugin sounds fantastic!

**Comment by zaguiini** [comment]
Yes @diegovilar I've been working on it. I just merged the branch and published the package. Please let me know if it does not work.

**Comment by diegovilar** [comment]
Great work! Just tested, seems to work, @zaguiini, but I'm getting warnings: #8
